namespace Workout.Properties.Services.Accessories
{
    internal class Languages
    {
        public Dictionary<string, string> MyLanguage { get; private set; }

        public Languages(string type)
        {
            if (type == Constans.LanguageName.Hu)
            {
                MyLanguage = new Dictionary<string, string>
                {
                    {"loginButton", "Bejelentkezés"},
                    {"registerButton", "Regisztráció"},
                    {"emailEntry", "Email cím"},
                    {"passwordEntry", "Jelszó"},
                    {"backButton", "Vissza"},
                    {"Belepesiadatad", "Add meg a belépési adataid."},
                    {"Keresztnev", "Keresztnév"},
                    {"Vezeteknev", "Vezetéknév"},
                    {"SzulDatum", "Születési dátum"},
                    {"EvEntry", "Év"},
                    {"NapEntry", "Nap"},
                    {"HonapEntry", "Hó"},
                    {"hibavezeteknev", "A Vezetéknév mező kitöltése kötelező."},
                    {"hibaKeresztnev", "A Keresztnév mező kitöltése kötelező."},
                    {"hibaemail", "Érvényes e-mail címet adj meg."},
                    {"hibadatum", "Add meg az érvényes születési dátumot."},
                    {"hibajelszo", "A jelszónak legalább 6 karakter hosszúnak kell lennie."},
                    {"Hiba", "Hiba"},
                    {"email1", "Üdvözöljük a Bull Plans Közösségben!"},
                    {"email2", "Kedves Felhasználó!"},
                    {"email3", "Örömmel értesítjük, hogy sikeresen regisztrált a szolgáltatásunkra."},
                    {"email4", "A fenti "},
                    {"email5", "regisztrációs kód"},
                    {"email6", " segítségével aktiválhatja fiókját."},
                    {"email7", "Amennyiben bármilyen kérdése van, keressen minket bizalommal."},
                    {"email8", "Üdvözlettel,"},
                    {"KodUjraKuldesButton", "Kód újraküldése"},
                    {"KodbekeresLabel", "Kód bekérése"},
                    {"hibaPrivacePolice", "El kell fogadni az adatkezelést"},
                    {"Elfogadom", "Elfogadom az "},
                    {"PrivacyPolicyLink", "adatkezelési tájékoztatót"},
                    {"helytelenbejelntkezes", "Helytelen jelszó vagy email"},
                    {"kesz", "Kész"},
                    {"Profil", "Profile"},
                    {"Uzenet", "Üzenet"},
                    {"Home", "Home"},
                    {"Stats", "Stats"},
                    {"Calendar", "Naptár"},
                    {"Send", "Küldés"},
                    {"uzenetIras", "Írj üzenetet..."},
                    {"het", "Hét"},
                    {"honap", "Hónap"},
                    {"foglaltaccount", "Sajnos máshol be vagy már jelentkezve"},
                    {"hibavalaszValamit", "Kérlek válasz valamit az opciók közül"},
                    {"hibaIrjValamit", "Kérlek irjd be minden  mezőre a megfelelő adataidat"},
                    {"gondemailiras", "Bármely kérdés vagy gond esetén írj nekünk email-t:"},
                    {"regMegerosites", "Regisztrációs megerősítés"},
                    {"noInternet", "Nincs internet kapcsolat"},
                    {"bolt", "Bolt"},
                    {"noEdzes", "nincs edzés"},
                    {"edzesDone", "Ezzel az edzéssel már végeztél"},
                    {"tooBig", "A kép mérete nem lehet nagyobb mint 1 MB."},
                    {"jpgPng", "Csak .jpg vagy .png képeket válassz!"},
                    {"WORK", "EDZÉS"},
                    {"pluszIdo", "mp"},
                    {"valaszKepet", "Válassz egy képet"},
                    {"hiba3", "Hiba történt a kép kiválasztásakor:"},
                    {"hiba4", "Nem sikerült a profilkép frissítése."},
                    {"edzesAtrakas", "Edzésnap átrakása"},
                    {"maiNapi", "Mai napi"},
                    {"edzes", "edzésterv"},
                    {"etrend", "étrend"},
                    {"mehet", "Mehet"},
                    {"logout", "Kijelentkezés"},
                    {"noTrain", "Nincs Edzés mára"},
                    {"train", "Edzés"},
                    {"suly", "Súly"},
                    {"darab", "Darab"},
                    {"vegeztel", "Végeztél"},
                    {"bemelegites", "Bemelegítés"},
                    {"nyujtas", "Nyújtás"},
                    {"start", "kezdés"},
                    {"kovetkezo", "Következő"},
                    {"pihenes", "PIHENÉS"},
                    {"shortDetail", "Rövid leirás:"},
                    {"kerdezAkarmit", "Nyugodtan tegyél fel bármilyen kérdést, és mi igyekszünk a lehető leghamarabb válaszolni."},
                    {"easy", "könnyü"},
                    {"medium", "közepes"},
                    {"hard", "nehéz"},
                    {"gratulalas", "Gratulálunk"},
                    {"elfelejtettJelszo", "Elfelejtettem a jelszavamat"},
                    {"elfelejtettJelszoEmail", "Elfelejtett jelszó"},
                    {"ujJelszoLabel", "Ad meg az új jelszót"},
                    {"client", "kliens"},
                    {"edzo", "edző"},
                    {"hibaUres", "nem hadhatsz üresen mezőt"},
                    {"hibaletezik", "Sajnos már létezik ilyen nevezetü ajánlat"},
                    {"Megerosites", "Megerősítés"},
                    {"biztosTorlesKerdes", "Biztos törölni szeretnéd ezt az ajánlatot: "},
                    {"igen", "Igen"},
                    {"megse", "Mégse"},

                };
            }
            else
            if (type == Constans.LanguageName.En)
            {
                MyLanguage = new Dictionary<string, string>
                {
                    {"loginButton", "Login"},
                    {"registerButton", "Registration"},
                    {"emailEntry", "Email address"},
                    {"passwordEntry", "Password"},
                    {"backButton", "Back"},
                    {"Belepesiadatad", "Enter your login details."},
                    {"Keresztnev", "First name"},
                    {"Vezeteknev", "Last name"},
                    {"SzulDatum", "Date of birth"},
                    {"EvEntry", "Year"},
                    {"NapEntry", "Day"},
                    {"HonapEntry", "Mo"},
                    {"hibavezeteknev", "Filling in the Surname field is mandatory."},
                    {"hibaKeresztnev", "Filling in the First name field is mandatory."},
                    {"hibaemail", "Enter a valid email address."},
                    {"hibadatum", "Enter a valid date of birth."},
                    {"hibajelszo", "The password must be at least 6 characters long."},
                    {"Hiba", "Fault"},
                    {"email1", "Welcome to the Bull Plans Community!"},
                    {"email2", "Dear User!"},
                    {"email3", "We are pleased to inform you that you have successfully registered for our service."},
                    {"email4", "Above "},
                    {"email5", "registration code"},
                    {"email6", " can be used to activate your account."},
                    {"email7", "If you have any questions, feel free to contact us."},
                    {"email8", "Best regards,"},
                    {"KodUjraKuldesButton", "Resend code"},
                    {"KodbekeresLabel", "Request a code"},
                    {"hibaPrivacePolice", "You must accept the data management"},
                    {"Elfogadom", "I accept that "},
                    {"PrivacyPolicyLink", "data management information"},
                    {"helytelenbejelntkezes", "Incorrect password or email"},
                    {"kesz", "Ready"},
                    {"Profil", "Profile"},
                    {"Uzenet", "Message"},
                    {"Home", "Home"},
                    {"Stats", "Stats"},
                    {"Calendar", "Calendar"},
                    {"Send", "Send"},
                    {"uzenetIras", "Write a message..."},
                    {"het", "Week"},
                    {"honap", "Month"},
                    {"foglaltaccount", "Unfortunately, you are already logged in elsewhere"},
                    {"hibavalaszValamit", "Please answer one of the options"},
                    {"hibaIrjValamit", "Please enter your correct data in each field"},
                    {"gondemailiras", "In case of any questions or problems, write us an email:"},
                    {"regMegerosites", "Registration confirmation"},
                    {"noInternet", "No internet connection"},
                    {"bolt", "Shop"},
                    {"noEdzes", "no training"},
                    {"edzesDone", "You are done with this workout"},
                    {"tooBig", "The size of the image cannot be larger than 1 MB."},
                    {"jpgPng", "Choose only .jpg or .png images!"},
                    {"WORK", "WORK"},
                    {"pluszIdo", "sec"},
                    {"valaszKepet", "Choose a picture"},
                    {"hiba3", "An error occurred while selecting the image:"},
                    {"hiba4", "Failed to update profile picture."},
                    {"edzesAtrakas", "Training day transfer"},
                    {"maiNapi", "Daily today"},
                    {"edzes", "training plan"},
                    {"etrend", "diet"},
                    {"mehet", "Go"},
                    {"logout", "Log out"},
                    {"noTrain", "No Training today"},
                    {"train", "Training"},
                    {"suly", "Weight"},
                    {"darab", "Piece"},
                    {"vegeztel", "Done"},
                    {"bemelegites", "Warming up"},
                    {"nyujtas", "Stretching"},
                    {"start", "Start"},
                    {"kovetkezo", "Following"},
                    {"pihenes", "REST"},
                    {"shortDetail", "Short description:"},
                    {"kerdezAkarmit", "Feel free to ask any questions, and we will do our best to respond as quickly as possible."},
                    {"easy", "easy"},
                    {"medium", "medium"},
                    {"hard", "hard"},
                    {"gratulalas", "Congratulation"},
                    {"elfelejtettJelszo", "I forgot my password"},
                    {"elfelejtettJelszoEmail", "Forgotten password"},
                    {"ujJelszoLabel", "Enter the new password"},
                    {"client", "client"},
                    {"edzo", "trainer"},
                    {"hibaUres", "you cannot leave a space empty"},
                    {"hibaletezik", "Unfortunately, an offer with this name already exists."},
                    {"Megerosites", "Confirmation"},
                    {"biztosTorlesKerdes", "Are you sure you want to delete this offer: "},
                    {"igen", "Yes"},
                    {"megse", "Cancel"},

                };
            }
        }
    }
}
